version: '3.3'
services:
  bar-db:
    image: mysql:5.7
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_DATABASE: 'bar-db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'bar'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'bar123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'bar123'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  
# Names our volume
volumes:
  my-db:
